### ISSUE TITLE
Circular dependency was not detected

### ISSUE THREAD

**Issue by cvle** [kolodny/jsan#13] opened 2017-03-09 07:58 UTC
We have a circular dependency but `jsan` doesn't seem to detect it:

`$.users[32].pm.users[0].pm.users[0].pm.users[0].pm.users[0].pm.users...`

until we have:
![screen shot 2017-03-09 at 14 21 02](https://cloud.githubusercontent.com/assets/14221600/23740889/3512b074-04d8-11e7-9464-4add1432c13a.png)

We are using https://github.com/zalmoxisus/redux-devtools-extension.

I even made a equality check console to see if we did sth wrong:

```js
users[32].pm.users[0] === users[32].pm.users[0].pm.users[0]
true
```

redux-devtools-extension version: 2.14.1
jsan version: 3.1.5

**Comment by zalmoxisus** [comment] 2017-03-09 08:33
I guess it's because every map instance is treated individually. See https://github.com/kolodny/jsan/pull/12#issuecomment-280603498.

I'll try to fix it.

**Comment by cvle** [comment] 2017-03-09 08:54
We just decided to remove all circular references from our store, so it won't affect us. I'll keep this issue open for others who might get bitten by it.

**Comment by vansosnin** [comment] 2018-01-09 09:35
Some additional info in referenced isse (above), if it helps.

**Comment by kolodny** [comment] 2018-04-29 03:16
I published `v3.1.10` which should catch these errors from now on. Let me know if that works.

**Comment by kolodny** [comment] 2018-05-15 16:11
Should be fixed not, feel free to reopen if the problem still exists

**Closed by kolodny** 2018-05-15 16:11 UTC

**Comment by 0xdevalias** [comment] 2019-05-20 06:26
Unsure if this is the root cause, but given it was referenced last time, wanted to point this out here: https://github.com/zalmoxisus/redux-devtools-extension/issues/649

My guess is that the react ref contains a circular reference to itself somewhere that is triggering this.
