### ISSUE TITLE
Crashes when trying to serialise a React ref

### ISSUE THREAD

**Issue by 0xdevalias** [kolodny/jsan#29] opened 2019-05-23 22:19 UTC
RE: https://github.com/zalmoxisus/redux-devtools-extension/issues/649

[Called here](https://github.com/zalmoxisus/redux-devtools-extension/blob/a3c1fe9817c8dd1fb28f24438b2aefd27814e8a2/src/app/api/index.js#L26)
```
return jsan.stringify(obj, windowReplacer, null, { circular: '[CIRCULAR]', date: true });
```

~Looking at the [default options](https://github.com/kolodny/jsan/blob/master/lib/index.js#L16-L29), I can't even see a `circular` key there.. so maybe redux-devtools is doing something wrong?~ _Edit: found it [buried away here](https://github.com/kolodny/jsan/blob/master/lib/cycle.js#L31)_

Presumably a similar infinite reference loop as https://github.com/kolodny/jsan/issues/13

----

When trying to view a React 'ref' in Redux DevTools, it endlessly cycles/crashes with an out of memory.

![image](https://user-images.githubusercontent.com/753891/58290448-19873500-7dfd-11e9-9e75-041845870682.png)

![image](https://user-images.githubusercontent.com/753891/58290305-a4b3fb00-7dfc-11e9-90ae-7e459adfa1f1.png)

Looks like it's around about here:
https://github.com/kolodny/jsan/blob/e7a4c68674251723dba444808f23cfb398442d6f/lib/cycle.js#L135-L153

A really simple test case caused about 1.4MB of output:
```
const inputRef = useRef(null)

  useEffect(
    () => {
      if (inputRef.current) {
        console.log('jsan', jsan.stringify({ inputRef }, null, null, true))
      }
    },
    [inputRef]
  )
```
```
<input {...inputProps} ref={inputRef} />
```
![image](https://user-images.githubusercontent.com/753891/58290985-0aa18200-7dff-11e9-8a30-9c2f4d7c5734.png)

From a naive skim of the output, it looks like might be following a path that leads it into the redux state store, where it finds the ref, and ends up in a similar path. I don't want to post the full stack here, but can send it to you privately if it would help.

**Comment by 0xdevalias** [comment] 2019-05-23 23:07
It may not be a proper 'deep fix', but a potentially easy way to shortcut this is to be able to stop parsing if we reference an `instanceof HTMLElement`?

![image](https://user-images.githubusercontent.com/753891/58292083-53f3d080-7e03-11e9-8987-881f9676aada.png)

**Comment by 0xdevalias** [comment] 2019-05-23 23:38
I also just noticed the `refs` option:
https://github.com/kolodny/jsan/blob/e7a4c68674251723dba444808f23cfb398442d6f/lib/cycle.js#L32

Used here:
https://github.com/kolodny/jsan/blob/e7a4c68674251723dba444808f23cfb398442d6f/lib/cycle.js#L108-L125

**Comment by kolodny** [comment] 2019-05-27 14:11
I'm still struggling to repro this in a simple stackblitz. This seems to work fine at https://stackblitz.com/edit/react-chs1wh?file=index.js. Is there some interaction needed to make this error out?

**Comment by 0xdevalias** [comment] 2019-05-28 01:40
It may be more specifically when it is a ref of an element that is also stored in redux (as per https://github.com/zalmoxisus/redux-devtools-extension/issues/649)

My guess is jsan is hitting the ref -> html element -> ... -> redux store -> ref -> html element -> etc... somehow.

**Comment by albertogasparin** [comment] 2020-05-25 12:40
I also faced this issue recently, with Chrome crashing bad when I'm storing a ref in a store. I guess the seriousness of the issue is related to the size of the app: I'm working on a very big React app so when `jsan` starts digging into the ref, finds `ownDocument` and starts serialising it too then makes Chrome run out of memory.

**Comment by kolodny** [comment] 2021-12-19 14:16
Closing for now since there isn't anything actionable here without a repro. Feel free to reopen with an example

**Closed by kolodny** 2021-12-19 14:16 UTC
